In [1]:
%run 02Development_Zone/db_connect.py

In [6]:
%%dev
insert into staff_bak0921
select * from staff;
commit;

Statement executed successfully.
Statement executed successfully.

In [9]:
%%dev
select * from staff_bak0921

,staff_id,location_id,job_id,first_name,last_name,home_phone,mobile_phone,hire_date,address,dob,emergency_number,wage_rate,wage_interval,payment_schedule,gender,is_married,is_active,is_permanent
0,10,10,10,Harry,Potter,333-9999,107890,2015-01-01T00:00:00,101 trace Townsville,1984-01-01T00:00:00,None,11.0,hour,week,M,T,T,F
1,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02T00:00:00,21 hello st. goodbyetown,1975-02-04T00:00:00,None,15.0,hour,week,F,T,T,F
2,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20T00:00:00,22 nice to meet you village,1983-03-03T00:00:00,None,19.0,hour,week,M,F,T,T
3,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01T00:00:00,101 trace Townsville,1984-01-01T00:00:00,None,11.0,hour,week,M,T,T,F
4,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02T00:00:00,21 hello st. goodbyetown,1975-02-04T00:00:00,None,15.0,hour,week,F,T,T,F
5,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20T00:00:00,22 nice to meet you village,1983-03-03T00:00:00,None,19.0,hour,week,M,F,T,T
6,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01T00:00:00,101 trace Townsville,1984-01-01T00:00:00,None,11.0,hour,week,M,T,T,F
7,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02T00:00:00,21 hello st. goodbyetown,1975-02-04T00:00:00,None,15.0,hour,week,F,T,T,F
8,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20T00:00:00,22 nice to meet you village,1983-03-03T00:00:00,None,19.0,hour,week,M,F,T,T
9,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01T00:00:00,101 trace Townsville,1984-01-01T00:00:00,None,11.0,hour,week,M,T,T,F
10,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02T00:00:00,21 hello st. goodbyetown,1975-02-04T00:00:00,None,15.0,hour,week,F,T,T,F
11,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20T00:00:00,22 nice to meet you village,1983-03-03T00:00:00,None,19.0,hour,week,M,F,T,T

In [49]:
%%dev 
update  staff_bak0921 
set mobile_phone = '207890'
where staff_id = 10;

select * from staff_bak0921

Oracle error: ORA-00933: SQL command not properly ended
Help: https://docs.oracle.com/error-help/db/ora-00933/

In [10]:
%%uat 
select * from staff

,staff_id,location_id,job_id,home_phone,mobile_phone,hire_date,address,dob,emergency_number,wage_rate,wage_interval,payment_schedule,gender,is_married,is_active,is_permanent,full_name
0,1,10,10,010-2001,13900000001,2025-06-19T00:00:00,北京市朝阳区,1999-12-31T00:00:00,None,12000.0,hour,month,M,T,T,T,**

In [18]:
ddl = get_ddl_dev("PACKAGE", "PKG_JTA", schema="DEV")
print(ddl)

CREATE OR REPLACE EDITIONABLE PACKAGE "DEV"."PKG_JTA"
IS
    -- some constants
    nat_insurance_rate CONSTANT NUMBER := 0.132;
    hlt_surcharge_rate CONSTANT NUMBER := 0.005;

    -- public procedures and functions
    PROCEDURE sp_process_payroll (
        p_date IN DATE
    );

    PROCEDURE sp_update_inventory (
        p_product_id IN cost_sales_tracker.product_id%TYPE,
        p_quantity IN NUMBER,
        p_new_cost IN cost_sales_tracker.cost_per_unit%TYPE
    );

    PROCEDURE sp_restock_urgent (
        p_staff_id IN staff.staff_id%TYPE
    );

    FUNCTION fn_get_last_cashier_payout (
        p_staff_id staff.staff_id%TYPE
    ) RETURN cashier_drawer_assignments.cash_amount_end%TYPE;

    FUNCTION fn_get_money_inflow (
        p_location_id locations.location_id%TYPE,
        p_start_date DATE,
        p_end_date DATE,
        p_type VARCHAR2 := 'cash'
    ) RETURN cashier_drawer_assignments.cash_amount_start%TYPE;

    PROCEDURE sp_update_taxes;

    TYPE price_change_record IS RECORD (
        product_id products.product_id%TYPE,
        product_name products.product_name%TYPE,
        date_changed price_history.start_date%TYPE,
        old_price price_history.price_rate%TYPE,
        new_price price_history.price_rate%TYPE,
        direction VARCHAR2(5)
    );

    TYPE price_changes_table IS TABLE OF price_change_record
    INDEX BY BINARY_INTEGER;

    FUNCTION fn_get_price_changes (
        p_product_id products.product_id%type,
        p_start_date DATE,
        p_end_date DATE
    ) RETURN price_changes_table;

    PROCEDURE sp_get_profits_for (
        p_start_date IN DATE,
        p_end_date IN DATE,
        p_goods_sold OUT NOCOPY NUMBER,
        p_gross_gain OUT NOCOPY NUMBER,
        p_costs OUT NOCOPY NUMBER,
        p_net_gain OUT NOCOPY NUMBER
    );

    PROCEDURE sp_get_recommended_price_for (
        p_product_id IN products.product_id%TYPE,
        p_avg_cost OUT NOCOPY products.price_rate%TYPE,
        p_old_price OUT NOCOPY products.price_rate%TYPE,
        p_new_price OUT NOCOPY products.price_rate%TYPE
    );

    PROCEDURE sp_evaluate_po_order_line (
        p_line_id IN purchase_order_lines.po_line_id%TYPE,
        p_not_enough_to_restock OUT NOCOPY BOOLEAN,
        p_not_at_min_level OUT NOCOPY BOOLEAN
    );

    PROCEDURE sp_lookup_barcode (
        p_barcode IN VARCHAR2,
        p_product_id OUT NOCOPY products.product_id%TYPE,
        p_product_name OUT NOCOPY products.product_name%TYPE,
        p_price_rate OUT NOCOPY products.price_rate%TYPE,
        p_tax_code OUT NOCOPY tax_rates.tax_code%TYPE,
        p_tax_rate OUT NOCOPY tax_rates.tax_rate%TYPE
    );

    PROCEDURE sp_update_from_bill (
        p_bill_id IN customer_bills.bill_id%TYPE
    );

    PROCEDURE sp_update_sales;

    FUNCTION fn_receive_payment (
        p_bill_id customer_bills.bill_id%TYPE,
        p_type customer_bills.payment_type%TYPE,
        p_amount customer_bills.payment_amount%TYPE
    ) RETURN NUMBER;

    PROCEDURE sp_add_item_to_bill (
        p_bill_id IN customer_bills.bill_id%TYPE,
        p_barcode IN products.barcode%TYPE
    );

    FUNCTION fn_get_tax_payment_due (
        p_tax_code tax_rates.tax_code%TYPE,
        p_year DATE
    ) RETURN NUMBER;

    FUNCTION fn_get_quantity_sold (
        p_product_id products.product_id%TYPE,
        p_location_id locations.location_id%TYPE,
        p_date_start DATE,
        p_date_end DATE
    ) RETURN NUMBER;

    PROCEDURE sp_stock_check (
        p_product_id IN products.product_id%TYPE,
        p_location_id IN locations.location_id%TYPE,
        p_value_counted INTEGER,
        p_in_stock OUT NOCOPY INTEGER
    );

    PROCEDURE sp_sunday_check (
        p_staff_id IN staff.staff_id%TYPE,
        p_month IN DATE,
        p_sundays OUT NOCOPY INTEGER,
        p_available OUT NOCOPY BOOLEAN
    );

    PROCEDURE sp_payout (
        p_staff_id IN staff.staff_id%TYPE,
        p_begin_date IN DATE,
        p_end_date IN DATE,
        p_gross_pay OUT NOCOPY payroll.gross_pay%TYPE,
        p_net_pay OUT NOCOPY payroll.net_pay%TYPE,
        p_hlt OUT NOCOPY payroll.hlt_surcharge_deduction%TYPE,
        p_nat OUT NOCOPY payroll.nat_insurance_deduction%TYPE,
        p_deductions OUT NOCOPY payroll.net_pay%TYPE
    );

    FUNCTION fn_get_name (
        p_staff_id staff.staff_id%TYPE
    ) RETURN VARCHAR2;

    -- end specification
END pkg_jta;

CREATE OR REPLACE EDITIONABLE PACKAGE BODY "DEV"."PKG_JTA" IS

    PROCEDURE sp_get_date (
        p_local_time OUT NOCOPY DATE
    );


    /*
        02
        Private procedure: Get Hours

        Given staff_id and time period, retrieve the regular,
        overtime and doubletime hours that a staff member has
        worked for.
    */
    PROCEDURE sp_get_hours (
        p_staff_id IN staff.staff_id%TYPE,
        start_date IN DATE,
        end_date IN DATE,
        basic OUT NOCOPY INTEGER,
        overtime OUT NOCOPY INTEGER,
        doubletime OUT NOCOPY INTEGER
    )
    IS
    BEGIN

        basic := 0;
        overtime := 0;
        doubletime := 0;

        SELECT nvl(SUM(hours_worked), 0) INTO doubletime
            FROM work_hours
            WHERE work_date BETWEEN start_date AND end_date
            AND staff_id = p_staff_id
            AND to_char(work_date, 'd') = '1';

        SELECT nvl(SUM(hours_worked), 0) INTO basic
            FROM work_hours
            WHERE work_date BETWEEN start_date AND end_date
            AND staff_id = p_staff_id
            AND to_char(work_date, 'd') != '1';

        IF basic > 40 THEN
            overtime := basic - 40;
            basic := 40;
        END IF;

    -- excpetions will be handled in called procedure
    END;


    /*
        03
        Process payroll

        Given any date in a week,
        retrieve the hours worked for each relevant employee from the
        work_hours table and populate the payroll table with payroll data
        for the week.

        Payroll Rules:
        > First forty hours is regular rate
        > Above forty hours is overtime x1.5
        > Sunday is double time

        Note1: this query only considers basic deductions. In the real world payroll
        is far more complex, however we couldn't find enough information and didn't
        have the time to learn all Accounting practices for this organization. This
        procedure can be modified easily to calculate other automatic deductions as needed.
    */
    PROCEDURE sp_process_payroll (
        p_date IN DATE
    )
    IS

        -- date range is Sunday to Sat for this day (friday)
        v_start_date DATE := TRUNC(p_date, 'DAY');
        v_end_date DATE := v_start_date + 6
            + numtodsinterval(23, 'hour')
            + numtodsinterval(59, 'minute')
            + numtodsinterval(59, 'second');

        -- gets a list of staff_ids for workers who worked for the week
        CURSOR c_staff_worked
            IS SELECT DISTINCT staff_id FROM work_hours
            WHERE work_date BETWEEN v_start_date AND v_end_date
            ORDER BY staff_id;

        doubletime payroll.hours_doubletime%TYPE;
        overtime payroll.hours_overtime%TYPE;
        basic payroll.hours_basic%TYPE;
        payrate staff.wage_rate%TYPE;
        gross_pay payroll.gross_pay%TYPE;
        nat_insurance_deduction payroll.nat_insurance_deduction%TYPE;
        hlt_surcharge_deduction payroll.hlt_surcharge_deduction%TYPE;
        net_pay payroll.net_pay%TYPE;

        v_count INTEGER := 0;

    BEGIN

        --dbms_output.put_line(to_char(v_start_date, 'yyyy-Mon-dd, HH24:MI:SS'));
        --dbms_output.put_line(to_char(v_end_date, 'yyyy-Mon-dd, HH24:MI:SS'));

       -- note that the procedure essentially do nothing if there are no work data for this week

        -- delete rows from payroll table if they already exist with current dates
        DELETE FROM payroll WHERE payroll.start_date = v_start_date AND payroll.end_date = v_end_date;

        -- for each staff that worked this week
        FOR current_staff IN c_staff_worked LOOP

            -- get the hours each staff member worked for
            sp_get_hours(current_staff.staff_id, v_start_date, v_end_date, basic, overtime, doubletime);
            -- get staff pay rate
            SELECT wage_rate INTO payrate FROM staff WHERE staff_id = current_staff.staff_id;
            -- calculate and save gross pay
            gross_pay := (basic * payrate) + (overtime * payrate * 1.5) + (doubletime * payrate * 2);
            -- calculate and save deductions
            nat_insurance_deduction := ROUND((gross_pay * nat_insurance_rate) / 3, 2);
            hlt_surcharge_deduction := ROUND((gross_pay * hlt_surcharge_rate), 2);
            -- calculate and save net pay
            net_pay := gross_pay - (nat_insurance_deduction + hlt_surcharge_deduction);

            -- insert new row into payroll table
            INSERT INTO payroll (
                payroll_id, staff_id, start_date, end_date,
                hours_basic, hours_overtime, hours_doubletime,
                basic_pay_rate, gross_pay,
                nat_insurance_deduction, hlt_surcharge_deduction,
                net_pay)
            VALUES (
                seq_payroll_id.NEXTVAL, current_staff.staff_id, v_start_date, v_end_date,
                basic, overtime, doubletime,
                payrate, gross_pay,
                nat_insurance_deduction, hlt_surcharge_deduction,
                net_pay);

                v_count := v_count + 1;
        END LOOP;

        IF v_count > 0 THEN
            COMMIT; -- commit when done and only when rows modified
        ELSE
            -- this exception is caught but not logged since it is trivial
            pkg_jta_error.sp_throw(-20201, 'There was no work hours recorded for this week: '
                || to_char(v_start_date, 'yyyy-Mon-dd, HH24:MI:SS') || ' to '
                || to_char(v_end_date, 'yyyy-Mon-dd, HH24:MI:SS'));
        END IF;

    EXCEPTION
        WHEN pkg_jta_error.invalid_input THEN
            pkg_jta_error.sp_show_in_console(SQLCODE, SQLERRM);
            ROLLBACK;
        WHEN OTHERS THEN
            -- all OTHER exceptions will be logged into error table...
            pkg_jta_error.sp_log_error(SQLCODE, SQLERRM);
            ROLLBACK;
    END sp_process_payroll;


    /*
        04
        Update Inventory

        Add or remove items from the overall inventory (all lcoations).
        This procedure also updates the average cost per unit whenever items are added.
        This procedure would be called whenever new items are recieved into the warehouse
        and also called for every item at the end of the day to remove items.

        The cost_sales_tracker table is slighlty redundant, however it improves speed when
        the supermarket needs to quickly check the inventory total for a product as well as
        its current avg_cost_price. This is a query that is run very often in the business as
        prices change daily for the organization.

        p_product_id:   the product to update
        p_quantity:     the quantity to update, negative numbers for removing, positive for adding
        p_new_cost:     the cost per unit when adding new items, set to null when removing
    */
    PROCEDURE sp_update_inventory (
        p_product_id IN cost_sales_tracker.product_id%TYPE,
        p_quantity IN NUMBER,
        p_new_cost IN cost_sales_tracker.cost_per_unit%TYPE
    )
    IS
        v_direction cost_sales_tracker.direction%TYPE := 'OUT';
        v_old_total cost_sales_tracker.total%TYPE;
        v_new_total cost_sales_tracker.total%TYPE;
        v_old_avg cost_sales_tracker.average_cost_per_unit%TYPE;
        v_new_avg cost_sales_tracker.average_cost_per_unit%TYPE;
        v_test_id products.product_id%TYPE;
        v_cost cost_sales_tracker.cost_per_unit%TYPE;

    BEGIN

        -- if zero quantity, raise error
        IF p_quantity = 0 THEN
            pkg_jta_error.sp_throw(-20201, 'cannot update a zero amount to inventory');
        END IF;


        -- if not actual product raise error
        BEGIN
            -- see if product id exists in product table
            SELECT product_id INTO v_test_id FROM products WHERE product_id = p_product_id;
        EXCEPTION
            WHEN no_data_found THEN
                pkg_jta_error.sp_throw(-20201, 'non existing product being updated to inventory');
            WHEN OTHERS THEN
                RAISE; -- outer procedure will deal with it
        END;


        -- get old total from db, if exists
        v_old_total := 0;
        BEGIN
            SELECT total INTO v_old_total
            FROM cost_sales_tracker
            WHERE product_id = p_product_id
            AND transaction_id IN (
            SELECT MAX(transaction_id) FROM cost_sales_tracker WHERE product_id = p_product_id);
        EXCEPTION
            WHEN no_data_found THEN
                -- if a previous entry was not made for this product it will remain zero
                NULL;
            WHEN OTHERS THEN
                RAISE;
        END;

        -- get old average if exists
        v_old_avg := 0;
        BEGIN
            SELECT average_cost_per_unit INTO v_old_avg
            FROM cost_sales_tracker
            WHERE product_id = p_product_id
            AND transaction_id IN (SELECT MAX(transaction_id) FROM cost_sales_tracker
            WHERE product_id = p_product_id);
        EXCEPTION
            WHEN no_data_found THEN
                -- if we never added a this product before, the old average is zero
                NULL;
            WHEN OTHERS THEN
                RAISE;
        END;


        -- update to new total,
        IF p_quantity > 0 THEN

            -- if adding an item, the cost must be positive, otherwise it is ignored
            IF p_new_cost <= 0 OR p_new_cost IS NULL THEN
                pkg_jta_error.sp_throw(-20201, 'cannot update inventory with non positive cost per unit');
            ELSE
                v_cost := p_new_cost;
            END IF;

            -- switch direction
            v_direction := 'IN';

            -- update new average
            v_new_avg := ROUND(((v_old_avg * v_old_total) + (p_quantity * p_new_cost) ) / (v_old_total + p_quantity), 2);

            -- calculate new total
            v_new_total := v_old_total + p_quantity;

        ELSE
            -- cost is ignored if removing items,
            v_cost := NULL;
            -- average also remains the same

            -- reduce quantity (its a negative number)
            v_new_total := v_old_total + p_quantity;

            -- throw error if negative
            IF v_new_total < 0 THEN
                pkg_jta_error.sp_throw(-20201, 'cannot remove more items than already exists in inventory');
            END IF;

            -- set old average as new average,
            -- if old average doesn't exist, the above negative error would have been thrown
            v_new_avg := v_old_avg;

        END IF;

        -- insert data into database
        INSERT INTO cost_sales_tracker (
            transaction_id, product_id, direction, date_time, quantity,
            total, average_cost_per_unit, cost_per_unit
        )
        VALUES (
            seq_transaction_id.NEXTVAL, p_product_id, v_direction, sysdate, p_quantity,
            v_new_total, v_new_avg, v_cost
        );

        COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            -- all exceptions will be logged into error table...
            pkg_jta_error.sp_log_error(SQLCODE, SQLERRM);
            ROLLBACK;
    END sp_update_inventory;


    /*
        05
        Restock Urgent

        Find items that need restocking, and automatically create a purchase order for them.
        The application can then allow the user to modify the purchase order to suit or delete
        it if they want. Items are choosen based on the re-order level stored for each product.

    */
    PROCEDURE sp_restock_urgent (
        p_staff_id IN staff.staff_id%TYPE
    )
    IS

        -- find products that need to be restocked
        -- by checking reorder-level and min_stock_level and quantity
        -- for a specific supplier's goods and location
        CURSOR urgent(
            p_supplier_id suppliers_per_products.supplier_id%TYPE,
            p_location_id inventory_by_location.location_id%TYPE
        ) IS
            SELECT inv.product_id, inv.reorder_level
            FROM inventory_by_location inv
            JOIN products pr ON (inv.product_id = pr.product_id)
            JOIN suppliers_per_products sp ON (sp.product_id = pr.product_id)
            WHERE inv.reorder_level <= (inv.min_stock_level - inv.quantity)
            AND inv.location_id = p_location_id AND sp.supplier_id = p_supplier_id;

        -- find distinct list of suppliers whose products need restocking
        CURSOR suppliers IS
            SELECT DISTINCT supplier_id, location_id
            FROM inventory_by_location inv
            JOIN products pr ON (inv.product_id = pr.product_id)
            JOIN suppliers_per_products sp ON (sp.product_id = pr.product_id)
            WHERE inv.reorder_level <= (inv.min_stock_level - inv.quantity);

        -- current purchase order being worked on
        v_current_po purchase_orders.po_id%TYPE;

    BEGIN

        -- for all suppliers who need restocking at each inventory location...
        FOR supplier IN suppliers LOOP
            -- create purchase orders for each supplier
            v_current_po := seq_po_id.NEXTVAL;
            INSERT INTO purchase_orders (po_id, supplier_id, staff_id, location_id, pending, approved, submitted_date)
            VALUES (v_current_po, supplier.supplier_id, p_staff_id, supplier.location_id, 'T', 'F', sysdate);

            -- add purchase order lines for this supplier
            FOR stock IN urgent(supplier.supplier_id, supplier.location_id) LOOP
                INSERT INTO purchase_order_lines (po_line_id, po_id, product_id, quantity, price_rate)
                VALUES(seq_po_line_id.NEXTVAL, v_current_po, stock.product_id, stock.reorder_level, NULL );
            END LOOP;

        END LOOP;

        COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            -- all exceptions will be logged into error table...
            pkg_jta_error.sp_log_error(SQLCODE, SQLERRM);
            ROLLBACK;
    END sp_restock_urgent;


    /*
        06
        Get last cashier payout.

        This function processes all bills created by a cashier
        for his/her last shift. This function would be called
        everytime a cashier finishes a shift in order to find out
        how much money should be recieved from them.
    */
    FUNCTION fn_get_last_cashier_payout (
        p_staff_id staff.staff_id%TYPE
    )
    RETURN cashier_drawer_assignments.cash_amount_end%TYPE
    IS
        v_assignment_id cashier_drawer_assignments.assignment_id%TYPE;
        v_cash_sum cashier_drawer_assignments.cash_amount_end%TYPE := 0;
    BEGIN

        -- get last cashier assingment (shift)
        SELECT MAX(assignment_id) INTO v_assignment_id
        FROM cashier_drawer_assignments
        WHERE staff_id = p_staff_id;


        -- we can sum the bill amounts, however we do something else instead
        /*
            SELECT SUM(nvl(payment_tender, 0)) INTO v_cash_sum
            FROM customer_bills b
            WHERE LOWER(payment_type) = 'cash'
            AND assignment_id = v_assignment_id;
        */

        -- we can get the payout from the assignment table instead,
        -- this is because we have now set up the package so that this table
        -- is automatically updated when the recieve_payment procedure is called
        -- to pay a bill.
        SELECT nvl(cash_amount_end, 0) INTO v_cash_sum
        FROM cashier_drawer_assignments
        WHERE assignment_id = v_assignment_id;

        -- return sum
        return v_cash_sum;

    EXCEPTION
        WHEN no_data_found THEN
            -- no shift for cashier, no cashier with that id etc...

In [ ]:
%%sql