In [8]:
%run 02Development_Zone/db_connect.py

In [9]:
%%dev 
select * from staff

,staff_id,location_id,job_id,first_name,last_name,home_phone,mobile_phone,hire_date,address,dob,emergency_number,wage_rate,wage_interval,payment_schedule,gender,is_married,is_active,is_permanent
0,10,10,10,Harry,Potter,333-9999,None,2015-01-01T00:00:00,101 trace Townsville,1984-01-01T00:00:00,None,11.0,hour,week,M,T,T,F
1,11,10,11,Sandy,Beach,454-8587,None,2015-02-02T00:00:00,21 hello st. goodbyetown,1975-02-04T00:00:00,None,15.0,hour,week,F,T,T,F
2,12,11,12,Jason,Bourne,457-8547,None,2015-01-20T00:00:00,22 nice to meet you village,1983-03-03T00:00:00,None,19.0,hour,week,M,F,T,T

In [10]:
%%uat 
select * from staff

,staff_id,location_id,job_id,home_phone,mobile_phone,hire_date,address,dob,emergency_number,wage_rate,wage_interval,payment_schedule,gender,is_married,is_active,is_permanent,full_name
0,1,10,10,010-2001,13900000001,2025-06-19T00:00:00,北京市朝阳区,1999-12-31T00:00:00,None,12000.0,hour,month,M,T,T,T,**