In [ ]:
%%sql
desc staff

In [4]:
%%sql
-- SELECT * FROM staff;
SELECT * FROM staff_bak0921;

,STAFF_ID,LOCATION_ID,JOB_ID,FIRST_NAME,LAST_NAME,HOME_PHONE,MOBILE_PHONE,HIRE_DATE,ADDRESS,DOB,EMERGENCY_NUMBER,WAGE_RATE,WAGE_INTERVAL,PAYMENT_SCHEDULE,GENDER,IS_MARRIED,IS_ACTIVE,IS_PERMANENT
0,10,10,10,Harry,Potter,333-9999,107890.0,2015-01-01,101 trace Townsville,1984-01-01,NaN,11.0,hour,week,M,T,T,F
1,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02,21 hello st. goodbyetown,1975-02-04,NaN,15.0,hour,week,F,T,T,F
2,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20,22 nice to meet you village,1983-03-03,NaN,19.0,hour,week,M,F,T,T
3,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01,101 trace Townsville,1984-01-01,NaN,11.0,hour,week,M,T,T,F
4,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02,21 hello st. goodbyetown,1975-02-04,NaN,15.0,hour,week,F,T,T,F
5,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20,22 nice to meet you village,1983-03-03,NaN,19.0,hour,week,M,F,T,T
6,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01,101 trace Townsville,1984-01-01,NaN,11.0,hour,week,M,T,T,F
7,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02,21 hello st. goodbyetown,1975-02-04,NaN,15.0,hour,week,F,T,T,F
8,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20,22 nice to meet you village,1983-03-03,NaN,19.0,hour,week,M,F,T,T
9,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01,101 trace Townsville,1984-01-01,NaN,11.0,hour,week,M,T,T,F
10,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02,21 hello st. goodbyetown,1975-02-04,NaN,15.0,hour,week,F,T,T,F
11,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20,22 nice to meet you village,1983-03-03,NaN,19.0,hour,week,M,F,T,T

In [11]:
%%sql
update staff_bak0921
set MOBILE_PHONE = 3
where staff_id = 11;

rollback;

select MOBILE_PHONE from staff_bak0921
where staff_id = 11;

   MOBILE_PHONE
0             3
1             3
2             3
3             3

In [ ]:
%%sql

In [10]:
%%sql
select MOBILE_PHONE from staff_bak0921
where staff_id = 11;

   MOBILE_PHONE
0             2
1             2
2             2
3             2