In [ ]:
%%sql
set serveroutput on; --for the output
declare
    price number(10,2);
    usenum number;
    usenum2 number(10,2);
    money number(10,2);
begin
    price:=2.45;
    usenum:=29;
    usenum2:=round(price/usenum);
    money:=price*usenum;
    dbms_output.put_line('money:'||money);
end;

In [ ]:
%%sql
set serveroutput on; --for the output
declare
    price number(10,2);
    usenum number;
    usenum2 number(10,2);
    money number(10,2);
begin
    price:=2.45;
    usenum:=29;
    usenum2:=round(price/usenum);
    money:=price*usenum;
    dbms_output.put_line('money:'||money);
end;
/

In [4]:
%%sql
-- SELECT * FROM staff;
SELECT * FROM staff_bak0921;

,STAFF_ID,LOCATION_ID,JOB_ID,FIRST_NAME,LAST_NAME,HOME_PHONE,MOBILE_PHONE,HIRE_DATE,ADDRESS,DOB,EMERGENCY_NUMBER,WAGE_RATE,WAGE_INTERVAL,PAYMENT_SCHEDULE,GENDER,IS_MARRIED,IS_ACTIVE,IS_PERMANENT
0,10,10,10,Harry,Potter,333-9999,107890.0,2015-01-01,101 trace Townsville,1984-01-01,NaN,11.0,hour,week,M,T,T,F
1,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02,21 hello st. goodbyetown,1975-02-04,NaN,15.0,hour,week,F,T,T,F
2,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20,22 nice to meet you village,1983-03-03,NaN,19.0,hour,week,M,F,T,T
3,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01,101 trace Townsville,1984-01-01,NaN,11.0,hour,week,M,T,T,F
4,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02,21 hello st. goodbyetown,1975-02-04,NaN,15.0,hour,week,F,T,T,F
5,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20,22 nice to meet you village,1983-03-03,NaN,19.0,hour,week,M,F,T,T
6,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01,101 trace Townsville,1984-01-01,NaN,11.0,hour,week,M,T,T,F
7,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02,21 hello st. goodbyetown,1975-02-04,NaN,15.0,hour,week,F,T,T,F
8,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20,22 nice to meet you village,1983-03-03,NaN,19.0,hour,week,M,F,T,T
9,10,10,10,Harry,Potter,333-9999,NaN,2015-01-01,101 trace Townsville,1984-01-01,NaN,11.0,hour,week,M,T,T,F
10,11,10,11,Sandy,Beach,454-8587,NaN,2015-02-02,21 hello st. goodbyetown,1975-02-04,NaN,15.0,hour,week,F,T,T,F
11,12,11,12,Jason,Bourne,457-8547,NaN,2015-01-20,22 nice to meet you village,1983-03-03,NaN,19.0,hour,week,M,F,T,T

In [11]:
%%sql
update staff_bak0921
set MOBILE_PHONE = 3
where staff_id = 11;

rollback;

select MOBILE_PHONE from staff_bak0921
where staff_id = 11;

   MOBILE_PHONE
0             3
1             3
2             3
3             3

In [ ]:
%%sql

In [10]:
%%sql
select MOBILE_PHONE from staff_bak0921
where staff_id = 11;

   MOBILE_PHONE
0             2
1             2
2             2
3             2

In [15]:
%%sql
    BEGIN
        -- process payroll for week without data
        pkg_jta.sp_process_payroll(TO_DATE('2025-05-13', 'yyyy-mm-dd'));
        -- throws an exception which is displayed and but not logged to error table
    END;
    /
    BEGIN
        -- process payroll for week with sample data
        pkg_jta.sp_process_payroll(TO_DATE('2025-03-13', 'yyyy-mm-dd'));
        -- sample data for this week will be processed
    END;
    /

    -- check payroll table to see three additions to it:
    SELECT * FROM payroll;

,PAYROLL_ID,STAFF_ID,START_DATE,END_DATE,HOURS_BASIC,HOURS_OVERTIME,HOURS_DOUBLETIME,BASIC_PAY_RATE,NAT_INSURANCE_DEDUCTION,HLT_SURCHARGE_DEDUCTION,COLA_DEDUCTION,PAYE_DEDUCTION,PENSION_DEDUCTION,HEALTH_PLAN_DEDUCTION,OTHER_DEDUCTION,DATE_STAFF_RECEIVED,GROSS_PAY,NET_PAY,NOTES
0,501,12,2025-05-11,2025-05-17 23:59:59,8,0,0.0,19.0,6.69,0.76,NaN,NaN,NaN,NaN,NaN,NaN,152.0,144.55,NaN
1,1,10,2015-05-01,2015-05-07,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-07,572.0,558.00,NaN
2,2,10,2015-05-08,2015-05-14,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-14,572.0,558.00,NaN
3,3,10,2015-05-15,2015-05-21,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-21,572.0,558.00,NaN
4,4,11,2015-05-01,2015-05-07,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-07,582.0,568.00,NaN
5,5,11,2015-05-08,2015-05-14,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-14,582.0,568.00,NaN
6,6,11,2015-05-15,2015-05-21,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-21,582.0,568.00,NaN
7,7,12,2015-05-01,2015-05-07,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-07,562.0,548.00,NaN
8,8,12,2015-05-08,2015-05-14,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-14,562.0,548.00,NaN
9,9,12,2015-05-15,2015-05-21,40,8,NaN,11.0,12.00,2.00,NaN,NaN,NaN,NaN,NaN,2015-05-21,562.0,548.00,NaN